server:
  port: 8082
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://47.101.212.134:3306/bbsgo_db?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
  mybatis-plus:
    global-config:
      db-config:
        #不刪除
        logic-delete-value: 1
        #
        logic-not-delete-value: 0
    mapper-locations: classpath*:mapper.sys/*.xml
    type-aliases-package: com.zzw.springboot.user