spring:
  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30
    # password:
    pool:
      minIdle: 1
      maxIdle: 10
      maxWait: 3
      maxActive: 8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.jdbc.Driver
    username: test
    password: 1qazxsw2
    url: jdbc:mysql://192.168.161.81:11811/bbsgo_db?characterEncoding=utf-8&useSSL=false
  mybatis-plus:
    global-config:
      db-config:
        #不刪除
        logic-delete-value: 1
        #
        logic-not-delete-value: 0
    mapper-locations: classpath*:mapper.sys/*.xml
    type-aliases-package: com.zzw.springboot.user