server:
  port: 8081
spring:
  # redis
  redis:
    host:
    port: 6378
    timeout: 3000
    #password:
    pool:
      minIdle: 1
      maxIdle: 10
      maxWait: 3
      maxActive: 8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username:
    password:
    url: jdbc:mysql://:3306/bbsgo_db?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
  mybatis-plus:
    global-config:
      db-config:
        #不刪除
        logic-delete-value: 1
        #
        logic-not-delete-value: 0
    mapper-locations: classpath*:mapper.sys/*.xml
    type-aliases-package: com.zzw.springboot.user

  application:
    name: product-service  #服务名
  cloud:
    nacos:
      discovery:
        server-addr:   #Nacos作为服务注册中心地址
        service: aaa
      config:
        server-addr:  #Nacos作为配置中心地址file-extension: yml  #指定yaml格式的配置
management:
  endpoint:
    web:
      exposure:
        inlcude: '*'