spring:
  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30
    # password:
    pool:
      minIdle: 1
      maxIdle: 10
      maxWait: 3
      maxActive: 8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/bbsgo_db?characterEncoding=utf-8&useSSL=false
  mybatis-plus:
    mapper-locations: classpath*:mapperConfig/*.xml