spring:
  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30
    # password:
    pool:
      minIdle: 1
      maxIdle: 10
      maxWait: 3
      maxActive: 8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: root
    password: qazwsx
    url: jdbc:mysql://localhost:3306/bbsgo_db?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
  mybatis-plus:
    global-config:
      db-config:
        #不刪除
        logic-delete-value: 1
        #
        logic-not-delete-value: 0
    mapper-locations: classpath*:mapper.sys/*.xml
    type-aliases-package: com.zzw.springboot.user